### ISSUE TITLE
App Sleeping on Heroku!

### ISSUE THREAD

**Issue by infernalslam** [mintmint95/gold-notify#12]
Hi @mintmint95 
I'm found issues something. when app will go to sleep after 1 hour of inactivity. 

my idea.
 1. heroku have a feature scheduler. you have to move function to schedule method.
 2. implement new cronjob call api itself for wake up a server.

I hope issuse is solving.

**Comment by TonPC64** [comment]
I think you can enhance this app witout create new cronjob 
just add add-ons heroku-scheduler to your app and add shell file to call api somthing like that.

<img width="648" alt="Screen Shot 2564-10-23 at 09 27 39" src="https://user-images.githubusercontent.com/12834601/138539302-6767cd09-df5c-4d43-bd77-06850f97fbda.png">

<img width="440" alt="Screen Shot 2564-10-23 at 09 26 58" src="https://user-images.githubusercontent.com/12834601/138539306-89c0277c-97dc-4c1e-bdd8-5aa3163c8592.png">

**Comment by mintmint95** [comment]
@infernalslam @TonPC64 I already fixed it. Thank you for taking time to comment the good recommend for me.
